# Generated by Django 5.1.7 on 2025-03-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(help_text='Height in cm', max_length=250)),
                ('steps', models.PositiveIntegerField(help_text='Number of steps')),
            ],
        ),
    ]
