# Generated by Django 5.1.7 on 2025-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='height',
            field=models.CharField(blank=True, help_text='Height in cm', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='steps',
            field=models.PositiveIntegerField(blank=True, help_text='Number of steps', null=True),
        ),
    ]
