# Generated by Django 5.1.7 on 2025-03-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_feeder_height_alter_feeder_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeder',
            old_name='height',
            new_name='mesuredHeight',
        ),
        migrations.RenameField(
            model_name='feeder',
            old_name='steps',
            new_name='stepCount',
        ),
    ]
