# Generated by Django 5.1.7 on 2025-03-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_feeder_mesuredheight_alter_feeder_stepcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='mesuredHeight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='stepCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
