# Generated by Django 5.1.7 on 2025-03-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_feeder_mesuredheight_alter_feeder_stepcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='conformationHeight',
            field=models.PositiveIntegerField(blank=True, help_text='conformationheight', null=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='targetHeight',
            field=models.PositiveIntegerField(help_text='target in mm', null=True),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='mesuredHeight',
            field=models.CharField(blank=True, help_text='mesuredHeight in cm', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='stepCount',
            field=models.PositiveIntegerField(blank=True, help_text='Number of stepCount', null=True),
        ),
    ]
