# Generated by Django 5.1.7 on 2025-03-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_feeder_conformationheight_feeder_targetheight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeder',
            name='targetHeight',
        ),
    ]
