# Generated by Django 5.0.6 on 2025-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_feeder_targetheight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='conformationHeight',
            field=models.CharField(blank=True, help_text='conformationheight in cm', max_length=250, null=True),
        ),
    ]
