# Generated by Django 5.1.7 on 2025-03-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_feeder_conformationheight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeder',
            name='conformationHeight',
        ),
        migrations.AddField(
            model_name='feeder',
            name='confirmationHeight',
            field=models.CharField(blank=True, help_text='conformationheight in cm ', max_length=250, null=True),
        ),
    ]
